INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(100,'hasith','Learn Cloud',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(110,'hasith','Learn AWS',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(120,'hasith','Learn Springboot',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(130,'hasith','Learn Docker',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(140,'hasith','Learn Python',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(150,'hasith','Learn No SQL Databases',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(160,'hasith','Learn functional programming',CURRENT_DATE,false);
INSERT INTO TODO(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE) VALUES(170,'hasith','Read books about Servlets',CURRENT_DATE,false);